### ISSUE TITLE
Ghosh


### ISSUE THREAD

**Issue by IamGhost76x** [IamGhost76x/reverse#5]
Traceback (most recent call last):      
- [ ]   File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 31, in <module>
    start(fakepyfile,mainpyfile)
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 30, in start
    exec(open(mainpyfile).read(),  __main__.__dict__)
  File "<string>", line 7
    on:
       ^
SyntaxError: invalid syntax

[Program finished]

**Comment by IamGhost76x** [comment]
Someone please touch this

**Comment by IamGhost76x** [comment]
> Traceback (most recent call last):      
> - [x]   File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 31, in <module>
>     start(fakepyfile,mainpyfile)
>   File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 30, in start
>     exec(open(mainpyfile).read(),  __main__.__dict__)
>   File "<string>", line 7
>     on:
>        ^
> SyntaxError: invalid syntax
> 
> [Program finished]
